#!/usr/bin/env bash
# ============================================================
# setup.sh — One-time bootstrapping script
# Run this BEFORE deploy.sh to prepare the AWS environment.
# ============================================================
set -euo pipefail

# ── Colours ──
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERR]${NC}  $*"; exit 1; }

# ── Config (override via env) ──
PROJECT_NAME="${PROJECT_NAME:-ecommerce-pipeline}"
AWS_REGION="${AWS_REGION:-us-east-1}"
ALERT_EMAIL="${ALERT_EMAIL:-you@example.com}"

AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
SCRIPTS_BUCKET="${PROJECT_NAME}-scripts-${AWS_ACCOUNT}"

echo ""
echo -e "${BOLD}🛒 E-Commerce Analytics Pipeline — Setup${NC}"
echo "  Project : $PROJECT_NAME"
echo "  Account : $AWS_ACCOUNT"
echo "  Region  : $AWS_REGION"
echo ""

# ── Destroy mode ──
if [[ "${1:-}" == "--destroy" ]]; then
    warn "DESTROY mode — deleting all resources …"
    echo ""
    read -rp "Type 'yes' to confirm: " CONFIRM
    [[ "$CONFIRM" != "yes" ]] && error "Aborted."

    info "Deleting CloudFormation stack …"
    aws cloudformation delete-stack \
        --stack-name "${PROJECT_NAME}-stack" \
        --region "$AWS_REGION" || warn "Stack not found"

    info "Emptying and deleting S3 buckets …"
    for suffix in bronze silver gold athena-results scripts; do
        BUCKET="${PROJECT_NAME}-${suffix}-${AWS_ACCOUNT}"
        if aws s3 ls "s3://${BUCKET}" 2>/dev/null; then
            aws s3 rm "s3://${BUCKET}" --recursive
            aws s3 rb "s3://${BUCKET}" --force
            success "Deleted s3://${BUCKET}"
        fi
    done
    success "Teardown complete."
    exit 0
fi

# ── Check prerequisites ──
info "Checking prerequisites …"
command -v aws  >/dev/null 2>&1 || error "AWS CLI not found. Install from https://aws.amazon.com/cli/"
command -v python3 >/dev/null 2>&1 || error "Python 3 not found."
aws sts get-caller-identity >/dev/null 2>&1 || error "AWS credentials not configured. Run 'aws configure'."
success "Prerequisites OK"

# ── Create scripts S3 bucket ──
info "Creating scripts bucket: s3://${SCRIPTS_BUCKET} …"
if aws s3 ls "s3://${SCRIPTS_BUCKET}" 2>/dev/null; then
    warn "Bucket already exists — skipping"
else
    if [[ "$AWS_REGION" == "us-east-1" ]]; then
        aws s3 mb "s3://${SCRIPTS_BUCKET}" --region "$AWS_REGION"
    else
        aws s3 mb "s3://${SCRIPTS_BUCKET}" \
            --region "$AWS_REGION" \
            --create-bucket-configuration LocationConstraint="$AWS_REGION"
    fi
    aws s3api put-public-access-block \
        --bucket "$SCRIPTS_BUCKET" \
        --public-access-block-configuration \
        "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
    success "Created s3://${SCRIPTS_BUCKET}"
fi

# ── Upload Glue scripts ──
info "Uploading Glue ETL scripts …"
aws s3 cp src/glue/bronze_to_silver.py \
    "s3://${SCRIPTS_BUCKET}/glue/bronze_to_silver.py"
aws s3 cp src/glue/silver_to_gold.py \
    "s3://${SCRIPTS_BUCKET}/glue/silver_to_gold.py"
aws s3 cp src/step_functions/pipeline_definition.json \
    "s3://${SCRIPTS_BUCKET}/step_functions/pipeline_definition.json"
success "Scripts uploaded"

# ── Package Lambda functions ──
info "Packaging Lambda functions …"
mkdir -p dist

(cd src/lambda/batch_ingestion && zip -q ../../dist/batch_ingestion.zip handler.py)
(cd src/lambda/pipeline_trigger && zip -q ../../dist/pipeline_trigger.zip handler.py)

aws s3 cp dist/batch_ingestion.zip  "s3://${SCRIPTS_BUCKET}/lambda/batch_ingestion.zip"
aws s3 cp dist/pipeline_trigger.zip "s3://${SCRIPTS_BUCKET}/lambda/pipeline_trigger.zip"
success "Lambda packages uploaded"

# ── Install Python deps ──
info "Installing Python dependencies …"
pip install -r src/data_generator/requirements.txt -q
success "Python deps installed"

# ── Write .env file ──
cat > .env << EOF
# Auto-generated by setup.sh — $(date)
export PROJECT_NAME="${PROJECT_NAME}"
export AWS_REGION="${AWS_REGION}"
export AWS_ACCOUNT="${AWS_ACCOUNT}"
export SCRIPTS_BUCKET="${SCRIPTS_BUCKET}"
export BRONZE_BUCKET="${PROJECT_NAME}-bronze-${AWS_ACCOUNT}"
export SILVER_BUCKET="${PROJECT_NAME}-silver-${AWS_ACCOUNT}"
export GOLD_BUCKET="${PROJECT_NAME}-gold-${AWS_ACCOUNT}"
export FIREHOSE_STREAM="${PROJECT_NAME}-order-stream"
export ALERT_EMAIL="${ALERT_EMAIL}"
EOF
success "Wrote .env"

echo ""
echo -e "${BOLD}✅ Setup complete! Next step:${NC}"
echo "   source .env && ./scripts/deploy.sh"
echo ""
